In [3]:
import torch

x = torch.tensor([5,7])

y = torch.tensor([7,5])

print(x*y)

tensor([35, 35])


In [4]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y =  torch.rand([2,5])
y

tensor([[0.7864, 0.2337, 0.6009, 0.7818, 0.6844],
        [0.6888, 0.9291, 0.7244, 0.2934, 0.4115]])

In [7]:
y.view([1,10])

tensor([[0.7864, 0.2337, 0.6009, 0.7818, 0.6844, 0.6888, 0.9291, 0.7244, 0.2934,
         0.4115]])