In [7]:
import torch

x = torch.tensor([5,7])

y = torch.tensor([7,5])

print(x*y)

tensor([35, 35])


In [2]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
x.shape

torch.Size([2, 5])

In [4]:
y =  torch.rand([2,5])
y

tensor([[0.1297, 0.5268, 0.8457, 0.5249, 0.7190],
        [0.4279, 0.4818, 0.3650, 0.0480, 0.1720]])

In [5]:
y.view([1,10])

tensor([[0.1297, 0.5268, 0.8457, 0.5249, 0.7190, 0.4279, 0.4818, 0.3650, 0.0480,
         0.1720]])

In [10]:
import torch
import torchvision
from torchvision import transforms, datasets

In [11]:
train = datasets.MNIST("", train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train=False, download=True, transform=transforms.Compose([transforms.ToTensor()]))

In [12]:
trainsets =  torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testsets =  torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)